sudo: required

services:
   - docker	
env:
   global:
    - REGISTRY: balidea
    - IMAGENAME: balidea/currency
    - TAG_VERSION: $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
    - TAG_LATEST: latest

script:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub"; fi
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi´
  - echo "LABEL GIT_COMMIT=$(git show-ref --heads | cut -f1 -d' ')" >> Dockerfile
  - echo "LABEL TAG_VERSION=$TAG_VERSION" >> Dockerfile
  - docker build --pull=true -t $IMAGENAME:$TAG_VERSION .
  - docker tag --force=true $IMAGENAME:$TAG_VERSION $IMAGENAME:$TAG_LATEST
  - docker push $IMAGENAME:$TAG_VERSION
  - docker push $IMAGENAME:$TAG_LATEST