sudo: required

services:
   - docker	
   
env:
  global:
    - REGISTRY: registry.blackwoodseven.com
    - IMAGENAME: $REGISTRY/$TRAVIS_REPO_SLUG
    - TAG_VERSION: $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
    - TAG_LATEST: latest

script:
  - find /home -name '*.pem' 
  - /sbin/ifconfig docker0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'
  - docker build --pull=true -t $IMAGENAME:$TAG_VERSION .