sudo: required

services:
   - docker	
   
env:
  global:
    - REGISTRY: registry.blackwoodseven.com
    - IMAGENAME: $REGISTRY/$TRAVIS_REPO_SLUG
    - TAG_VERSION: $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
    - TAG_LATEST: latest

script:
  - ifconfig docker0
  - ifconfig docker0 | grep 'inet addr:' | cut -d: -f2
  - docker login --username=balidea --password=balidea --email=veronica.otero@balidea.com
  - ls  /home/travis/.docker
  - sudo mkdir /home/travis/.docker/certs
  - cd  /home/travis/.docker/certs
  - docker run -v $PWD:/work -it nginx openssl genrsa -des3 -out /work/server.key.protected 2048
  - docker run -v $PWD:/work -it nginx openssl req -new -key /work/server.key.protected -out /work/server.csr
  - docker run -v $PWD:/work -it nginx openssl rsa -in /work/server.key.protected -out /work/server.key
  - docker run -v $PWD:/work -it nginx openssl x509 -req -days 365 -in /work/server.csr -signkey /work/server.key -out /work/server.crt
  - ls
  - docker build --pull=true -t $IMAGENAME:$TAG_VERSION .