sudo: required

services:
   - docker	
   
env:
  global:
    - REGISTRY: registry.blackwoodseven.com
    - IMAGENAME: $REGISTRY/$TRAVIS_REPO_SLUG
    - TAG_VERSION: $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
    - TAG_LATEST: latest

script:
  - ifconfig docker0
  - ifconfig docker0 | grep 'inet addr:' | cut -d: -f2
  - docker login --username=balidea --password=balidea --email=veronica.otero@balidea.com
  - ls  /home/travis/.docker
  - sudo mkdir /home/travis/.docker/certs
  - sudo cd  /home/travis/.docker/certs
  - sudo openssl genrsa -out ca-key.pem 2048;
  - sudo openssl req -newkey rsa:2048 -days 1000 -nodes -keyout server-key.pem -out server-req.pem;
  - sudo openssl x509 -req -in server-req.pem -days 1000 -CA ca-cert.pem -CAkey ca-key.pem -set_serial 01 -out server-cert.pem;
  - sudo openssl req -newkey rsa:2048 -days 1000 -nodes -keyout key.pem -out req.pem;
  - sudo openssl x509 -req -in req.pem -days 1000 -CA ca-cert.pem -CAkey ca-key.pem -set_serial 01 -out cert.pem;
  - docker build --pull=true -t $IMAGENAME:$TAG_VERSION .