sudo: required
language: java
jdk: oraclejdk7
services:
   - docker	
env:
   global:
    - REGISTRY: balidea
    - IMAGENAME: $REGISTRY/currency
script: 
  - mvn test 
  - mvn clean install -DskipTests=true
before_install:
  - echo "Testing Docker Hub credentials"
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - echo "Docker Hub credentials are working"
after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub"; fi
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - export TAG='if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi'
  - cd .docker
  - docker build -t $IMAGENAME .
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker tag $REGISTRY:$COMMIT $REGISTRY:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REGISTRY