sudo: required

services:
   - docker	
   
env:
  global:
    - REGISTRY: registry.blackwoodseven.com
    - IMAGENAME: $REGISTRY/$TRAVIS_REPO_SLUG
    - TAG_VERSION: $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
    - TAG_LATEST: latest

script:
  - ifconfig docker0
  - ifconfig docker0 | grep 'inet addr:' | cut -d: -f2
  - docker login --username=balidea --password=balidea --email=veronica.otero@balidea.com
  - sudo find  /home/travis/.docker -name '*.pem' 
  - docker build --pull=true -t $IMAGENAME:$TAG_VERSION .